"""Initial database schema

Revision ID: 374cd1bb0593
Revises: 
Create Date: 2026-01-26 21:11:45.792457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374cd1bb0593'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('market_probability', sa.Float(), nullable=True),
    sa.Column('context_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecasts_method_timestamp', 'forecasts', ['method', 'timestamp'], unique=False)
    op.create_index('idx_forecasts_ticker_timestamp', 'forecasts', ['ticker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_forecasts_ticker'), 'forecasts', ['ticker'], unique=False)
    op.create_index(op.f('ix_forecasts_timestamp'), 'forecasts', ['timestamp'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('strike_date', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_markets_category_status', 'markets', ['category', 'status'], unique=False)
    op.create_index('idx_markets_status_close_time', 'markets', ['status', 'close_time'], unique=False)
    op.create_index(op.f('ix_markets_category'), 'markets', ['category'], unique=False)
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    op.create_index(op.f('ix_markets_ticker'), 'markets', ['ticker'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_published', 'news', ['published_at'], unique=False)
    op.create_index('idx_news_source_published', 'news', ['source', 'published_at'], unique=False)
    op.create_index(op.f('ix_news_article_id'), 'news', ['article_id'], unique=True)
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_source'), 'news', ['source'], unique=False)
    op.create_table('news_market_relevance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('matched_keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_relevance_news_ticker', 'news_market_relevance', ['news_id', 'ticker'], unique=False)
    op.create_index('idx_relevance_ticker_score', 'news_market_relevance', ['ticker', 'relevance_score'], unique=False)
    op.create_index(op.f('ix_news_market_relevance_news_id'), 'news_market_relevance', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_market_relevance_ticker'), 'news_market_relevance', ['ticker'], unique=False)
    op.create_table('polymarket_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('yes_price', sa.Float(), nullable=True),
    sa.Column('no_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_polymarket_condition_timestamp', 'polymarket_prices', ['condition_id', 'timestamp'], unique=False)
    op.create_index('idx_polymarket_ticker_timestamp', 'polymarket_prices', ['ticker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_polymarket_prices_condition_id'), 'polymarket_prices', ['condition_id'], unique=False)
    op.create_index(op.f('ix_polymarket_prices_ticker'), 'polymarket_prices', ['ticker'], unique=False)
    op.create_index(op.f('ix_polymarket_prices_timestamp'), 'polymarket_prices', ['timestamp'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_position_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_timestamp', 'portfolio_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_timestamp'), 'portfolio_snapshots', ['timestamp'], unique=True)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Integer(), nullable=False),
    sa.Column('market_price', sa.Integer(), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_ticker_side', 'positions', ['ticker', 'side'], unique=False)
    op.create_index(op.f('ix_positions_ticker'), 'positions', ['ticker'], unique=True)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('yes_bid', sa.Integer(), nullable=True),
    sa.Column('yes_ask', sa.Integer(), nullable=True),
    sa.Column('no_bid', sa.Integer(), nullable=True),
    sa.Column('no_ask', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prices_ticker_timestamp', 'prices', ['ticker', 'timestamp'], unique=False)
    op.create_index('idx_prices_timestamp', 'prices', ['timestamp'], unique=False)
    op.create_index(op.f('ix_prices_ticker'), 'prices', ['ticker'], unique=False)
    op.create_index(op.f('ix_prices_timestamp'), 'prices', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('fill_id', sa.String(length=100), nullable=True),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id')
    )
    op.create_index('idx_trades_status_timestamp', 'trades', ['status', 'timestamp'], unique=False)
    op.create_index('idx_trades_ticker_timestamp', 'trades', ['ticker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=True)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    op.create_index(op.f('ix_trades_timestamp'), 'trades', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_timestamp'), table_name='trades')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_index('idx_trades_ticker_timestamp', table_name='trades')
    op.drop_index('idx_trades_status_timestamp', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_prices_timestamp'), table_name='prices')
    op.drop_index(op.f('ix_prices_ticker'), table_name='prices')
    op.drop_index('idx_prices_timestamp', table_name='prices')
    op.drop_index('idx_prices_ticker_timestamp', table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_positions_ticker'), table_name='positions')
    op.drop_index('idx_positions_ticker_side', table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolio_snapshots_timestamp'), table_name='portfolio_snapshots')
    op.drop_index('idx_snapshots_timestamp', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_polymarket_prices_timestamp'), table_name='polymarket_prices')
    op.drop_index(op.f('ix_polymarket_prices_ticker'), table_name='polymarket_prices')
    op.drop_index(op.f('ix_polymarket_prices_condition_id'), table_name='polymarket_prices')
    op.drop_index('idx_polymarket_ticker_timestamp', table_name='polymarket_prices')
    op.drop_index('idx_polymarket_condition_timestamp', table_name='polymarket_prices')
    op.drop_table('polymarket_prices')
    op.drop_index(op.f('ix_news_market_relevance_ticker'), table_name='news_market_relevance')
    op.drop_index(op.f('ix_news_market_relevance_news_id'), table_name='news_market_relevance')
    op.drop_index('idx_relevance_ticker_score', table_name='news_market_relevance')
    op.drop_index('idx_relevance_news_ticker', table_name='news_market_relevance')
    op.drop_table('news_market_relevance')
    op.drop_index(op.f('ix_news_source'), table_name='news')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_index(op.f('ix_news_article_id'), table_name='news')
    op.drop_index('idx_news_source_published', table_name='news')
    op.drop_index('idx_news_published', table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_markets_ticker'), table_name='markets')
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_index(op.f('ix_markets_category'), table_name='markets')
    op.drop_index('idx_markets_status_close_time', table_name='markets')
    op.drop_index('idx_markets_category_status', table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_forecasts_timestamp'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_ticker'), table_name='forecasts')
    op.drop_index('idx_forecasts_ticker_timestamp', table_name='forecasts')
    op.drop_index('idx_forecasts_method_timestamp', table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
